version: "3.9"

services:
  db:
    image: postgres:13-alpine
    restart: always
    env_file:
     - ./.env.db
    ports:
     - "5432:5432"
  django:
     build: ./
     ports:
      - "8000:8000"
     restart: always
     env_file:
      - ./.env.dj
     depends_on:
       - db
